### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by denzo** [JustParsa/atom-ember-components#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-ember-components](https://github.com/JustParsa/atom-ember-components) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/denissalimovs/.atom/packages/atom-ember-components/lib/atom-ember-components.js:66

TypeError: Cannot read property 'path' of null
    at Object.displayRenderingComponentsFooter (/packages/atom-ember-components/lib/atom-ember-components.js:66:43)
    at /packages/atom-ember-components/lib/atom-ember-components.js:29:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
     -9:39.3.0 core:undo (input.hidden-input)
  4x -9:36.8.0 core:redo (input.hidden-input)
     -9:34.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-ember-components 0.3.1 
atom-ternjs 0.18.2 
docblockr 0.9.4 
ember-tabs 2.4.1 
git-plus 7.3.3 
pretty-json 1.6.2 
```

**Comment by JustParsa** [comment]
@denzo I appreciate you taking the time to file a bug. I've pushed a hot fix that should address this. Please let me know if you're still having any issues. 

I plan on doing considerable iteration on this package including cleanup and bug fixes in the very near future, so any and all feedback is appreciated! :)
